SKILLS: str = ".pv-skill-categories-section ol li span.pv-skill-category-entity__name-text"
EXP_BLOCK: str = "pv-entity__position-group-pager"
PAGE_LOADED: str = "pv-profile-section"
ABOUT: str = '.pv-about-section p span:not(.lt-line-clamp__ellipsis--dummy)'
SHOW_MORE_EXP: str = 'pv-profile-section__see-more-inline'
HIDE_EXP: str = 'pv-profile-section__see-less-inline'
SHOW_MORE_EXP_DESC: str = "inline-show-more-text__button"
HIDE_EXP_DESC: str = "inline-show-more-text__link-container-expanded"
SHOW_MORE_ABOUT: str = "#line-clamp-show-more-button"
SHOW_MORE_SKILLS: str = "pv-skills-section__additional-skills"
EXP_DESC: str = 'pv-entity__extra-details'
CONTACT_NAME: str = '.pv-top-card--list:first-child li:first-child'
SINGLE_EXP: str = "a > div > h3"
MULTIPLE_EXP: str = "ul h3 span:not(.visually-hidden)"
REGION: str = ".pv-entity__location span:not(.visually-hidden)"
DATE_RANGE: str = ".pv-entity__date-range >:not(.visually-hidden)"
EXP_LENGTH: str = ".pv-entity__bullet-item-v2"
COMPANY_NAME: str = "pv-entity__secondary-title"
ALTERNATE_COMPANY_NAME: str = "h3 span:not(.visually-hidden)"
LAZY_LOADING_IMG: str = "artdeco-loader__bars"
SIGN_IN_BUTTON: str = "sign-in-form"